tempo = input("Insira o tempo percorrido: ")
tempo = float(tempo)
velocidade = input("Insira a Velocidade: ")
velocidade = float(velocidade)
distancia = (tempo*velocidade)
litros_usados = (distancia/12)
print (distancia)
print (velocidade)
print (tempo)
print (litros_usados)
